
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/transportador?useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
